INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES (18, 'Mariusz', 'Pastuszka');
INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES (25, 'Maria', 'Polak');
INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES (40, 'Eryk', 'Kowalski');